server:
  port: 8085

#spring.data.jpa.repositories.enabled=true
#spring.jackson.serialization.fail-on-empty-beans=false
#spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

spring:
  datasource:
    platform: postgres
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
    url: jdbc:postgresql://localhost:5432/spring-erp-model
    username: postgres
    password: root
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    database: POSTGRESQL
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQL95Dialect